# Generated by Django 6.1 on 2026-09-13 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Category Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Category Status')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Source Name')),
                ('url', models.URLField(unique=True, verbose_name='Source URL')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tag Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tag Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Tag Status')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Vacancy Title')),
                ('company', models.CharField(max_length=100, verbose_name='Vacancy Company')),
                ('position', models.CharField(max_length=100, verbose_name='Vacancy Position')),
                ('work_type', models.CharField(choices=[('OF', 'Office'), ('RE', 'Remote'), ('HY', 'Hybrid')], max_length=2, verbose_name='Vacancy Type')),
                ('grade', models.CharField(blank=True, choices=[('IN', 'Intern'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('AR', 'Architect')], max_length=2, verbose_name='Vacancy Grade')),
                ('salary_min', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Vacancy Salary')),
                ('salary_max', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Vacancy Salary')),
                ('salary_currency', models.CharField(blank=True, max_length=3, verbose_name='Vacancy Salary Currency')),
                ('experience_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vacancy Experience Min')),
                ('experience_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vacancy Experience Max')),
                ('priorities', models.TextField(blank=True, verbose_name='Vacancy Priorities')),
                ('requirements', models.TextField(blank=True, verbose_name='Vacancy Requirements')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Vacancy Responsibilities')),
                ('employment', models.CharField(blank=True, max_length=100, verbose_name='Vacancy Employment')),
                ('reg_method', models.CharField(blank=True, max_length=100, verbose_name='Vacancy Registration')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Vacancy Email')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Vacancy Phone')),
                ('telegram', models.CharField(blank=True, max_length=200, verbose_name='Vacancy Telegram')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Vacancy Location')),
                ('source_url', models.URLField(unique=True, verbose_name='Vacancy Source URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Vacancy Status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='vacancy.category', verbose_name='Vacancy Category')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='vacancy.source', verbose_name='Vacancy Source')),
                ('tags', models.ManyToManyField(blank=True, related_name='vacancies', to='vacancy.tag', verbose_name='Vacancy Tags')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
